### ISSUE TITLE
Vhost set in config is not available on this machine / ident

### ISSUE THREAD

**Issue by auwaerter** [eggheads/eggdrop-docker#30]
Hello together,

i'm having some questions about the eggdrop, as i quite had a long break within the whole configuration/installation part of it. I'm running a vps with four ipv4 IPs, where i'm now trying to migrate my existing eggdrop(s) (`v1.8.4` to `v1.9.5`) by using docker compose. I'm facing some trouble using the `set vhost <IP/DNS>` option.

If activated, i'm receiving the following error message:

`Failed connect to my.fancy.irc.network (Vhost set in config is not available on this machine)`

Not using it, is causing that the default `ens18:1` from the host is being used, not even `ens18` what confuses me a little.

Anyway, i've tried to work with networks:

```yaml
services:
  eggdrop_one:
    image: eggdrop:latest
    networks:
     - eggdrop_one:
         ipv4_address: 33.33.33.1
      dns:
        - 8.8.8.8
        - 1.1.1.1
```
Where i could specify the IP i want to assign to the service. That worked, but after that the DNS resolution did not. What can i do to use that specific IP: 33.33.33.1 (just an example) to use to connect to the IRC Server?

**Question two:** Before i've used docker, i had only one binary/installation of eggdrop installed, using a specific user. From there i was using several eggdrop config files, what made it quite lightweight. Now using docker compose, what is the recommened way to have this multi instance setup? Having several services within the `docker-compose.yaml`?

**Question three:** How do i connect oidentd using the docker compose setup? What is the recommended way to get rid of the `~`?

Thanks! :)
