### ISSUE TITLE
Latest stable is crashing

### ISSUE THREAD

**Issue by MyWay** [eggheads/eggdrop-docker#31]
Hi, I'm running eggdrop on arm, until 1.9.5 everything works fine, but when updating to latest stable, I get the following and then the container is crashing:
```
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
(1/4) Installing tzdata (2024b-r0)
(2/4) Installing tcl (8.6.14-r1)
(3/4) Installing tcl-lib (1.21-r1)
(4/4) Installing tcl-tls (1.7.22-r4)
Executing busybox-1.36.1-r29.trigger
OK: 33 MiB in 24 packages
```

Unfortunately the log isn't very helpful.

My docker compose:
```
services:
  eggdrop:
    image: eggdrop:1.9.5
    command:
      - /bin/sh
      - -c
      - |
        apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community tcl-lib tcl-tls && \
        exec /home/eggdrop/eggdrop/entrypoint.sh eggdrop.conf
```

**Comment by DArqueBishop** [comment]
I'm having the same issue. Running `docker logs` shows nothing; the container keeps crashing and restarting before anything is logged, apparently. The system I'm attempting the run the container on is an x86_64-based kvm VPS.

The following is my compose file:
```
services:
     eggdrop:
          image: eggdrop:stable
          container_name: eggdrop
          command: eggdrop.conf
          volumes:
               - "/var/local/eggdrop/data:/home/eggdrop/eggdrop/data"
               - "/var/local/eggdrop/contrib:/home/eggdrop/eggdrop/contrib"
               - "/var/local/eggdrop/logs:/home/eggdrop/eggdrop/logs"
               - "/var/local/eggdrop/netbots:/home/eggdrop/eggdrop/netbots"
          ports:
               - 4175:4175
               - 2010-2020:2010-2020
          restart: always
          stdin_open: true
```

**Comment by DArqueBishop** [comment]
I ran `docker compose up` as opposed to `docker compose up -d`, and got this output before stopping with Ctrl-C:

```
root@athena:~/compose/eggdrop# docker compose up
[+] Running 2/2
 ✔ Network eggdrop_default  Created                                         0.2s
 ✔ Container eggdrop        Created                                         0.1s
Attaching to eggdrop
eggdrop exited with code 0
eggdrop exited with code 0
eggdrop exited with code 1
eggdrop exited with code 1
eggdrop exited with code 1
eggdrop exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container eggdrop  Stopped                                               0.0s
```

**Comment by vanosg** [comment]
@DArqueBishop is this a new/fresh instance of eggdrop, or are you using an existing config file in the data directory?

**Comment by DArqueBishop** [comment]
It’s using an existing config file.

**Comment by vanosg** [comment]
@MyWay I would take a look at the example docker-compose file the docs provide at https://github.com/eggheads/eggdrop-docker/blob/master/docker-compose.yml  and add in the required environmental variables (and other required settings), or mount an existing eggdrop configuration file. 

@DArqueBishop I would double-check that the path and config file you are using exist where docker thinks it is- my working theory on this is the NICK and SERVER variables are not set in the docker-compose file, and there is no eggdrop config file it can find to load these variables from. For fun, you could try adding the environment variables into your compose file and see if that fixes it to narrow down the issue.

**Comment by MyWay** [comment]
> @MyWay I would take a look at the example docker-compose file the docs provide at https://github.com/eggheads/eggdrop-docker/blob/master/docker-compose.yml  and add in the required environmental variables (and other required settings), or mount an existing eggdrop configuration file. 
> 
> @DArqueBishop I would double-check that the path and config file you are using exist where docker thinks it is- my working theory on this is the NICK and SERVER variables are not set in the docker-compose file, and there is no eggdrop config file it can find to load these variables from. For fun, you could try adding the environment variables into your compose file and see if that fixes it to narrow down the issue.

Keep in mind that it's working for both of us with the previous version. Any var break change? Any different setting for config file location? Because otherwise it can't be that.

**Comment by vanosg** [comment]
@MyWay If what you pasted  is truly your full docker-compose file, then it should never have started with any version. What would be most helpful here is running it in foreground  as I suggested above (no -d) and sharing the output.

**Comment by MyWay** [comment]
It was just to give you the command I used:

```
services:
  eggdrop:
    image: eggdrop:1.9.5
    container_name: eggdrop
    command:
      - /bin/sh
      - -c
      - |
        apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community tcl-lib tcl-tls && \
        exec /home/eggdrop/eggdrop/entrypoint.sh eggdrop.conf
    restart: always
    volumes:
      - ./data:/home/eggdrop/eggdrop/data
      - ./scripts2:/home/eggdrop/eggdrop/scripts2
      - ./Bot:/home/eggdrop/eggdrop/Bot
    env_file:
      - .env
    stdin_open: true
    tty: true
```

Change 1.9.5 to latest version to make it crash when starting. No error shown. Logs are those I pasted in the initial post.

> [@MyWay](https://github.com/MyWay) If what you pasted is truly your full docker-compose file, then it should never have started with any version. What would be most helpful here is running it in foreground as I suggested above (no -d) and sharing the output.
